name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/pharmacy-backend

            git pull origin main

            /usr/bin/npm install
            /usr/bin/npm run build

            /usr/bin/pm2 restart pharmacy-api || /usr/bin/pm2 start dist/main.js --name pharmacy-api